<!-- Start of Air Quality Row -->
<script type='text/javascript'>showChart("AQI-UV");</script>

<div class="row">
    <div class="col-sm-12 forecast-title" style="text-align:center;">Air Quality + UV Index <span class="bold"> (as of $current.dateTime.format('%m-%d-%Y %H:%M')) </span></div>           
</div>
<div class="entry-content AQI-UV-outer">
    <div class="col-sm-4 mx-auto">
        <div id="aqiPM25" style="margin-top:30px;"></div>
    </div>    
    <div class="col-sm-4 mx-auto">
        <div id="aqiPM10" style="margin-top:30px;"></div>
    </div> 
    <div class="col-sm-4 mx-auto">
        <div id="UVIndex" style="margin-top:30px;"></div>
    </div>       
</div>   
<div class="clear"></div>

<!-- End of Air Quality Row-->