<div class="entry-content about-outer" itemprop="text">
    <div class="container">
        <div class="row" style="margin:10px;">
            <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#current-atl">Current</a></li>
                <li><a data-toggle="tab" href="#atl-2day">2 Days</a></li>
                <li><a data-toggle="tab" href="#atl-5day">5 Days</a></li>
            </ul>

            <div class="tab-content" style="text-align: center;">
                <div id="current-atl" class="tab-pane fade in active">
                    <img src="https://www.nhc.noaa.gov/xgtwo/two_atl_0d0.png" style="max-width:100%; height:auto" alt="TC Activity">
                </div>
                <div id="atl-2day" class="tab-pane fade">
                    <img src="https://www.nhc.noaa.gov/xgtwo/two_atl_2d0.png" style="max-width:100%; height:auto" alt="TC Activity 2d">
                </div>
                <div id="atl-5day" class="tab-pane fade">
                    <img src="https://www.nhc.noaa.gov/xgtwo/two_atl_5d0.png" style="max-width:100%; height:auto" alt="TC Activity 5d">
                </div>
            </div>
        </div>
    </div>
</div>